### ISSUE TITLE
Make the parser its own feature

### ISSUE THREAD

**Issue by neonmoe** [Teascade/glerminal#1]
As a feature, the `regex` crate could be moved to the parser's deps and save some space if the user doesn't need the parser.

**Comment by Teascade** [comment]
The parser itself (The mod of it on `lib.rs`) should also definitely be separated into a feature with `#[cfg(features = "parser")]` tag, if it wasn't obvious enough. This should ne included as a default feature though.

With this issue the documentation should also be updated to read that this is now a feature that can be optionally removed.
