### ISSUE TITLE
Basic example panics on macOS 10.13.3

### ISSUE THREAD

**Issue by valrus** [Teascade/glerminal#25]
The Mac is an iMac (Retina 5K, 27-inch, 2017).

### Versions of libraries used (if applicable):
- GLerminal: 0.1.5

Dependencies:
```
   Compiling void v1.0.2
   Compiling utf8-ranges v1.0.0
   Compiling khronos_api v2.1.0
   Compiling adler32 v1.0.2
   Compiling core-foundation-sys v0.5.1
   Compiling foreign-types-shared v0.1.1
   Compiling ucd-util v0.1.1
   Compiling num-traits v0.2.2
   Compiling block v0.1.6
   Compiling sfl_parser v1.3.0
   Compiling bitflags v1.0.1
   Compiling lazy_static v1.0.0
   Compiling libc v0.2.39
   Compiling byteorder v1.2.1
   Compiling regex v0.2.10
   Compiling cfg-if v0.1.2
   Compiling unreachable v1.0.0
   Compiling inflate v0.3.4
   Compiling foreign-types v0.3.2
   Compiling regex-syntax v0.5.3
   Compiling xml-rs v0.7.0
   Compiling log v0.4.1
   Compiling thread_local v0.3.5
   Compiling malloc_buf v0.0.6
   Compiling memchr v2.0.1
   Compiling shared_library v0.1.8
   Compiling deflate v0.7.17
   Compiling num-integer v0.1.36
   Compiling objc v0.2.2
   Compiling aho-corasick v0.6.4
   Compiling core-foundation v0.5.1
   Compiling num-iter v0.1.35
   Compiling gl_generator v0.9.0
   Compiling png v0.11.0
   Compiling core-graphics v0.13.0
   Compiling cocoa v0.14.0
   Compiling gleam v0.4.26
   Compiling glutin v0.13.1
   Compiling gl v0.10.0
   Compiling winit v0.11.2
   Compiling cgl v0.2.1
```

### Expected Behaviour
Basic example in the README compiles and runs.

### Actual Behaviour
```
❯ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/rugue`
thread 'main' panicked at 'Box<Any>', /Users/valrus/.cargo/registry/src/github.com-1ecc6299db9ec823/glerminal-0.1.5/src/display.rs:41:24
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: glerminal::display::Display::new
   7: glerminal::terminal::Terminal::new
   8: glerminal::terminal::TerminalBuilder::build
   9: rugue::main
  10: __rust_maybe_catch_panic
  11: std::rt::lang_start
  12: main
```

### Steps to reproduce this behaviour
1. Start a new project with `cargo new --bin rugue`
2. `cd rugue`
3. Add `glerminal = "0.1.5"` to `[dependencies]` in `Cargo.toml`
4. Copy/paste the README example into `src/main.rs`
5. `cargo run`

**Comment by Teascade** [comment]
This seems like a driver issue, since the panic occurs while creating a GlContext, I just made a patch that should clarify this error a bit and print out your OpenGL version (if any is found). Can you run `cargo update` and try again?

**Comment by valrus** [comment]
I'll give it a try when I get home tonight. Thanks!

FWIW I ran `glxinfo` and got 2.1 last night, if that's relevant at all.

**Comment by Teascade** [comment]
Ah yes, that is quite relevant. The minimum version required is 3.1, at least for now. How is your macOS?  Any mac computers newer than 2008/2009 should support 3.1 (you can check yours probably somewhere around this table [https://support.apple.com/en-us/HT202823](https://support.apple.com/en-us/HT202823)), if that's the case, you're probably missing some drivers, in which case your computer is using an integrated graphics card that natively only support OpenGL 2.1

**Comment by knipferrc** [comment]
Just wanted to report, I tried the latest and received this error on the latest 15in macbook pro.

thread 'main' panicked at 'Invalid version value from GL driver: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by valrus** [comment]
Quite new (last year) iMac, running the newest OS. From some cursory research it looked like there's a way to make things use a newer version, but not from the user side? I'm not sure; I'm a little bit out of my depth here.

**Comment by Teascade** [comment]
@knipferrc Well that seems like quite a major issue in your GL drivers; the program simply tried to fetch the OpenGL version number and even that failed (seen in `Invalid version value from GL driver`) You should probably see if there's a way to install any graphics drivers. I just did a quick patch, if you could try it, it might give out more information for why did it fail, though I doubt it.

For both of your issues this seems very weird though. I recommend seeing if there are some updates to the OS you could download, but other than that, I'm not sure why is the OpenGL support is so low.

**Comment by knipferrc** [comment]
Here is the error that I am seeing with the latest: 

thread 'main' panicked at 'Invalid version value from GL driver: '4.1 ATI-1.60.26': ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:916:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Seems im using open gl 4.1

**Comment by valrus** [comment]
I wonder if this is relevant? https://github.com/tomaka/glutin/issues/176

In particular: "When creating an OpenGL context on OS X, you seem to always get an 2.1 context, in order to get one of the newer versions, you need to specify that version in the attributes of your NSOpenGLPixelFormat instance." That's been fixed, I gather, but maybe you need to do something special to get a different context on OS X?

No idea if that applies here; if not, I'm out of ideas. Thanks for taking a look in any case! 😅

**Comment by Teascade** [comment]
@knipferrc Alright, it does seem like your OpenGL version should be up to date, the version parser was just broken (since unfortunately I didn't the third version digit to be missing in any version fetches). Either way, the parse-method has now been fixed (I even tried with your specific text), and the OpenGL version requirement has been upped to 3.3, which is more usually supported, so that *might* fix the shaders crashing in your case earlier.

@valrus Good idea, but apparently the issue has been closed down 3 years ago, so probably not relevant. I'll try to look if glutin has any related issues though, since it is entirely possible.

**Comment by Teascade** [comment]
It seems the issue has been resolved, though I'm waiting for @valrus to confirm this also, though for you it might actually be a driver issue (since glxinfo printed 2.1), though it might be that glxinfo just printed out a wrong version number, or you looked at the wrong profile (glxinfo prints all the OpenGL profiles, so it will show up 2.1 even though there might be 4.1 etc. also)

**Comment by valrus** [comment]
I'll follow up later with a run of the new code and some more detailed glxinfo output.

**Comment by valrus** [comment]
Hey, I lied about the glxinfo output because the example works with 0.1.8! Thanks!

**Comment by Teascade** [comment]
Great to hear! You probably didn't lie but just read the wrong profile from the glxinfo, since it prints all of your OpenGL profiles, meaning it tells you all the different versions of OpenGL that your drivers support, including 2.1 (which is probably supported by every computer manufactured after the 21st century)

Anyways, since this has now been resolved, I'll close this issue.
